# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  images: |
    - name: cilium
      image: ghcr.io/bitmoa/cilium:1.18.1-debian-12-r0
    - name: cilium-operator
      image: ghcr.io/bitmoa/cilium-operator:1.18.1-debian-12-r0
    - name: cilium-proxy
      image: ghcr.io/bitmoa/cilium-proxy:1.34.5-debian-12-r0
    - name: hubble-relay
      image: ghcr.io/bitmoa/hubble-relay:1.18.1-debian-12-r0
    - name: hubble-ui
      image: ghcr.io/bitmoa/hubble-ui:0.13.3-debian-12-r0
    - name: hubble-ui-backend
      image: ghcr.io/bitmoa/hubble-ui-backend:0.13.3-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 1.18.1
dependencies:
- condition: etcd.enabled
  name: etcd
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - cilium-database
  version: 12.x.x
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
description: Cilium is an eBPF-based networking, observability, and security for Linux
  container management platforms like Docker and Kubernetes.
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/cilium/img/cilium-stack-220x234.png
keywords:
- cilium
- cni
- networking
- observability
- security
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: cilium
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/cilium
- https://github.com/bitmoa/containers/tree/main/bitmoa/cilium
- https://github.com/bitmoa/containers/tree/main/bitmoa/cilium-operator
- https://github.com/bitmoa/containers/tree/main/bitmoa/cilium-proxy
- https://github.com/bitmoa/containers/tree/main/bitmoa/hubble-relay
- https://github.com/bitmoa/containers/tree/main/bitmoa/hubble-ui
- https://github.com/bitmoa/containers/tree/main/bitmoa/hubble-ui-backend
version: 3.1.9
