# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  images: |
    - name: rabbitmq
      image: ghcr.io/bitmoa/rabbitmq:4.1.3-debian-12-r0
    - name: rabbitmq-cluster-operator
      image: ghcr.io/bitmoa/rabbitmq-cluster-operator:2.16.1-debian-12-r0
    - name: rmq-default-credential-updater
      image: ghcr.io/bitmoa/rmq-default-credential-updater:1.0.8-debian-12-r0
    - name: rmq-messaging-topology-operator
      image: ghcr.io/bitmoa/rmq-messaging-topology-operator:1.17.4-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 2.16.1
dependencies:
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
description: The RabbitMQ Cluster Kubernetes Operator automates provisioning, management,
  and operations of RabbitMQ clusters running on Kubernetes.
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/rabbitmq-cluster-operator/img/rabbitmq-cluster-operator-stack-220x234.png
keywords:
- rabbitmq
- operator
- infrastructure
- message queue
- AMQP
kubeVersion: '>= 1.19.0-0'
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: rabbitmq-cluster-operator
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/rabbitmq-cluster-operator
version: 4.4.34
