# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  images: |
    - name: cassandra
      image: ghcr.io/bitmoa/cassandra:5.0.5-debian-12-r0
    - name: jaeger
      image: ghcr.io/bitmoa/jaeger:2.9.0-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 2.9.0
dependencies:
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
- condition: cassandra.enabled
  name: cassandra
  repository: https://charts-dev.bitmoa.net/bitmoa/
  version: 12.x.x
description: Jaeger is a distributed tracing system. It is used for monitoring and
  troubleshooting microservices-based distributed systems.
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/jaeger/img/jaeger-stack-220x234.png
keywords:
- jaeger
- tracing
- monitoring
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: jaeger
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/jaeger
version: 6.0.5
