# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Database
  images: |
    - name: neo4j
      image: ghcr.io/bitmoa/neo4j:5.26.11-debian-12-r0
    - name: os-shell
      image: ghcr.io/bitmoa/os-shell:12-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 5.26.11
dependencies:
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
description: Neo4j is a high performance graph store with all the features expected
  of a mature and robust database, like a friendly query language and ACID transactions.
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/neo4j/img/neo4j-stack-220x234.png
keywords:
- database
- neo4j
- graph
- graphdb
- graph-database
- nosql
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: neo4j
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/neo4j
- https://github.com/bitmoa/containers/tree/main/bitmoa/neo4j
- https://github.com/neo4j/neo4j
version: 0.4.14
