# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  images: |
    - name: kong
      image: ghcr.io/bitmoa/kong:3.9.1-debian-12-r0
    - name: kong-ingress-controller
      image: ghcr.io/bitmoa/kong-ingress-controller:3.5.1-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 3.9.1
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts-dev.bitmoa.net/bitmoa/
  version: 16.x.x
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
- condition: cassandra.enabled
  name: cassandra
  repository: https://charts-dev.bitmoa.net/bitmoa/
  version: 12.x.x
description: Kong is an open source Microservice API gateway and platform designed
  for managing microservices requests of high-availability, fault-tolerance, and distributed
  systems.
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/kong/img/kong-stack-220x234.png
keywords:
- kong
- ingress
- openresty
- controller
- http
- web
- www
- reverse proxy
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: kong
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/kong
version: 15.4.22
