# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Analytics
  images: |
    - name: multus-cni
      image: ghcr.io/bitmoa/multus-cni:4.2.2-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 4.2.2
dependencies:
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
description: Multus is a CNI plugin for Kubernetes clusters. Written in Go, features
  adding multiple network interfaces to pods.
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/multus-cni/img/multus-cni-stack-220x234.png
keywords:
- multus-cni
- cni
- kubernetes
- networking
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: multus-cni
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/multus-cni
version: 2.2.21
