# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Database
  images: |
    - name: os-shell
      image: ghcr.io/bitmoa/os-shell:12-debian-12-r0
    - name: scylladb
      image: ghcr.io/bitmoa/scylladb:2025.2.2-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 2025.2.2
dependencies:
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
description: ScyllaDB is an open-source, distributed NoSQL wide-column data store.
  Written in C++, it is designed for high throughput and low latency, compatible with
  Apache Cassandra.
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/scylladb/img/scylladb-stack-220x234.png
keywords:
- scylladb
- database
- nosql
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: scylladb
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/scylladb
version: 5.0.6
