# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Analytics
  images: |
    - name: superset
      image: ghcr.io/bitmoa/superset:5.0.0-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 5.0.0
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts-dev.bitmoa.net/bitmoa/
  version: 22.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts-dev.bitmoa.net/bitmoa/
  version: 16.x.x
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
description: Superset is a modern data exploration and data visualization platform.
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/superset/img/superset-stack-220x234.png
keywords:
- superset
- analytics
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: superset
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/superset
- https://github.com/bitmoa/containers/tree/main/bitmoa/superset
- https://github.com/apache/superset
version: 5.0.0
