# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  images: |
    - name: os-shell
      image: ghcr.io/bitmoa/os-shell:12-debian-12-r0
    - name: vault
      image: ghcr.io/bitmoa/vault:1.20.2-debian-12-r0
    - name: vault-csi-provider
      image: ghcr.io/bitmoa/vault-csi-provider:1.5.1-debian-12-r0
    - name: vault-k8s
      image: ghcr.io/bitmoa/vault-k8s:1.7.0-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 1.20.2
dependencies:
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
description: Vault is a tool for securely managing and accessing secrets using a unified
  interface. Features secure storage, dynamic secrets, data encryption and revocation.
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/vault/img/vault-stack-220x234.png
keywords:
- security
- secrets
- injection
- vault
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: vault
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/vault
version: 1.9.0
