# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  images: |
    - name: mariadb
      image: ghcr.io/bitmoa/mariadb:12.0.2-debian-12-r0
    - name: os-shell
      image: ghcr.io/bitmoa/os-shell:12-debian-12-r0
    - name: postgresql
      image: ghcr.io/bitmoa/postgresql:17.6.0-debian-12-r0
    - name: seaweedfs
      image: ghcr.io/bitmoa/seaweedfs:3.96.0-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 3.96.0
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - seaweedfs-database
  version: 22.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - seaweedfs-database
  version: 16.x.x
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
description: SeaweedFS is a simple and highly scalable distributed file system.
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/seaweedfs/img/seaweedfs-stack-220x234.png
keywords:
- seaweedfs
- storage
- blob-storage
- file-storage
- object-storage
- s3
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: seaweedfs
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/seawwedfs
- https://github.com/bitmoa/containers/tree/main/bitmoa/seaweedfs
version: 6.0.1
