# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  images: |
    - name: minio
      image: ghcr.io/bitmoa/minio:2025.7.23-debian-12-r0
    - name: minio-client
      image: ghcr.io/bitmoa/minio-client:2025.7.21-debian-12-r0
    - name: minio-object-browser
      image: ghcr.io/bitmoa/minio-object-browser:2.0.2-debian-12-r0
    - name: os-shell
      image: ghcr.io/bitmoa/os-shell:12-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 2025.7.23
dependencies:
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
description: MinIO(R) is an object storage server, compatible with Amazon S3 cloud
  storage service, mainly used for storing unstructured data (such as photos, videos,
  log files, etc.).
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/minio/img/minio-stack-220x234.png
keywords:
- minio
- storage
- object-storage
- s3
- cluster
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: minio
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/minio
version: 17.0.21
