# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Forum
  images: |
    - name: discourse
      image: ghcr.io/bitmoa/discourse:3.5.0-debian-12-r0
    - name: os-shell
      image: ghcr.io/bitmoa/os-shell:12-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 3.5.0
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts-dev.bitmoa.net/bitmoa/
  version: 22.X.X
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts-dev.bitmoa.net/bitmoa/
  version: 16.X.X
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
description: Discourse is an open source discussion platform with built-in moderation
  and governance systems that let discussion communities protect themselves from bad
  actors even without official moderators.
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/discourse/img/discourse-stack-220x234.png
keywords:
- community
- forum
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
- email: username.taken@gmail.com
  name: paulczar
- email: preteluca@gmail.com
  name: lucaprete
name: discourse
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/discourse
version: 17.0.1
