# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Analytics
  images: |
    - name: alertmanager
      image: ghcr.io/bitmoa/alertmanager:0.28.1-debian-12-r0
    - name: blackbox-exporter
      image: ghcr.io/bitmoa/blackbox-exporter:0.27.0-debian-12-r0
    - name: prometheus
      image: ghcr.io/bitmoa/prometheus:3.5.0-debian-12-r0
    - name: prometheus-operator
      image: ghcr.io/bitmoa/prometheus-operator:0.85.0-debian-12-r0
    - name: thanos
      image: ghcr.io/bitmoa/thanos:0.39.2-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 0.85.0
dependencies:
- condition: exporters.enabled,exporters.node-exporter.enabled
  name: node-exporter
  repository: https://charts-dev.bitmoa.net/bitmoa/
  version: 4.x.x
- condition: exporters.enabled,exporters.kube-state-metrics.enabled
  name: kube-state-metrics
  repository: https://charts-dev.bitmoa.net/bitmoa/
  version: 5.x.x
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
- name: kube-prometheus-crds
  repository: file://./charts/kube-prometheus-crds
  version: 0.x.x
description: Prometheus Operator provides easy monitoring definitions for Kubernetes
  services and deployment and management of Prometheus instances.
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/prometheus-operator/img/prometheus-operator-stack-220x234.png
keywords:
- prometheus
- alertmanager
- operator
- monitoring
kubeVersion: '>= 1.16.0-0'
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: kube-prometheus
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/kube-prometheus
version: 11.3.10
