# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: %%CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE%%
  licenses: Apache-2.0
apiVersion: v2
appVersion: %%UPSTREAM_PROJECT_VERSION%%
dependencies:
  - condition: SUBCHART_NAME.enabled
    name: SUBCHART_NAME
    repository: https://charts-dev.bitmoa.net/bitmoa/
    version: %%MAJOR_SUBCHART_VERSION_(A.X.X)%%
  - name: common
    repository: https://charts-dev.bitmoa.net/bitmoa/
    tags:
      - bitmoa-common
    version: 2.x.x
description: %%DESCRIPTION%%
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/%%IMAGE_NAME%%/img/%%IMAGE_NAME%%-stack-220x234.png
keywords:
  - %%UPSTREAM_PROJECT_KEYWORD%%
  - %%UPSTREAM_PROJECT_KEYWORD%%
  - ...
maintainers:
  - name: Bitmoa
    url: https://github.com/bitmoa/charts
name: %%CHART_NAME%%
sources:
  - https://github.com/bitmoa/charts/tree/main/bitmoa/%%IMAGE_NAME%%
  - https://github.com/bitmoa/containers/tree/main/bitmoa/%%IMAGE_NAME%%
  - %%UPSTREAM_PROJECT_SOURCE_CODE_URL%%
  - ...
version: 0.1.0
