# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Database
  images: |
    - name: os-shell
      image: ghcr.io/bitmoa/os-shell:12-debian-12-r0
    - name: pgpool
      image: ghcr.io/bitmoa/pgpool:4.6.3-debian-12-r0
    - name: postgres-exporter
      image: ghcr.io/bitmoa/postgres-exporter:0.17.1-debian-12-r0
    - name: postgresql-repmgr
      image: ghcr.io/bitmoa/postgresql-repmgr:17.6.0-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 17.6.0
dependencies:
- name: common
  repository: https://charts-dev.bitmoa.net/bitmoa/
  tags:
  - bitmoa-common
  version: 2.x.x
description: This PostgreSQL cluster solution includes the PostgreSQL replication
  manager, an open-source tool for managing replication and failover on PostgreSQL
  clusters.
home: https://bitmoa.net
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/postgresql/img/postgresql-stack-220x234.png
keywords:
- postgresql
- repmgr
- pgpool
- postgres
- database
- sql
- replication
- cluster
- high availability
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: postgresql-ha
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/postgresql-ha
version: 16.3.2
